# Generated by Django 4.1.2 on 2022-12-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_ID', models.CharField(max_length=200)),
                ('coach_image', models.ImageField(upload_to='images')),
                ('coach_name', models.CharField(max_length=200)),
                ('coach_age', models.IntegerField()),
                ('coach_emailID', models.CharField(max_length=200)),
                ('coach_mobileNum', models.CharField(max_length=200)),
                ('coach_addressLine1', models.CharField(max_length=200)),
                ('coach_addressLine2', models.CharField(max_length=200)),
                ('coach_addressLine3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_ID', models.CharField(max_length=200)),
                ('player_image', models.ImageField(upload_to='images')),
                ('player_name', models.CharField(max_length=200)),
                ('player_age', models.IntegerField()),
                ('player_emailID', models.CharField(max_length=200)),
                ('player_position', models.CharField(max_length=200)),
                ('player_height', models.CharField(max_length=200)),
                ('player_gaurdianName', models.CharField(max_length=200)),
                ('player_jerseyNum', models.IntegerField(max_length=200)),
                ('player_mobileNum', models.CharField(max_length=200)),
                ('player_addressLine1', models.CharField(max_length=200)),
                ('player_addressLine2', models.CharField(max_length=200)),
                ('player_addressLine3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_ID', models.CharField(max_length=200)),
                ('team_image', models.ImageField(upload_to='images')),
                ('team_name', models.CharField(max_length=200)),
            ],
        ),
    ]
